apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cx-0125-traceability.fullname" . }}-secret
  labels:
    {{- include "cx-0125-traceability.labels" . | nindent 4 }}
type: Opaque
data:
  appApiKey: {{ .Values.secrets.appApiKey | b64enc | quote }}
  edcManagementApiKey: {{ .Values.secrets.edcManagementApiKey | b64enc | quote }}
