name: Docker Build and Publish References

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'CX-0125-traceability/**'
      - '.github/workflows/docker-publish-references.yml'
  push:
    branches: [ "main" ]
    paths:
      - 'CX-0125-traceability/**'
      - '.github/workflows/docker-publish-references.yml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REFERENCES_IMAGE_NAME: ${{ github.repository }}/cx-0125-traceability-reference
  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for References Docker
        id: meta-references
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REFERENCES_IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push References Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./CX-0125-traceability
          push: true
          tags: ${{ steps.meta-references.outputs.tags }}
          labels: ${{ steps.meta-references.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

